name: loopay
description: A fintech app for Kenyans abroad - Send money in minutes, not days.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animations
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  flutter_animate: ^4.2.0+1
  
  # Navigation
  go_router: ^12.1.3
  
  # State Management
  provider: ^6.1.1
  
  # Form Validation
  form_validator: ^2.1.1
  
  # Icons
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  
  # Utils
  intl: ^0.18.1
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
